#
# Module manifest for module 'PowerType'
#
# Generated by: Peter Andersson
#
# Generated on: 7/12/2023
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '0.1.0'

# Supported PSEditions
CompatiblePSEditions = 'Core'

# ID used to uniquely identify this module
GUID = '20950bd3-90ca-4d9a-917a-7b76ba6327e5'

# Author of this module
Author = 'Peter Andersson'

# Company or vendor of this module
CompanyName = ''

# Copyright statement for this module
Copyright = 'Peter Andersson. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Module providing recommendations for common tools - This module requires PowerShell 7.2 and PSReadLine 2.2.0.

Suggestions must be activated:
- Enable-PowerType:        Activate the suggestions
- Disable-PowerType:       Disable the suggestions
- Get-PowerTypeStatus      Gets the status of PowerType, this is useful for troubleshooting issues
- Get-PowerTypeHistory     Gets the prediction history of PowerType, this is useful for troubleshooting issues

For more information on PowerType, please visit the following: https://github.com/AnderssonPeter/PowerType'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.2'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('PowerType.dll')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = 'Enable-PowerType', 'Disable-PowerType', 'Get-PowerTypeStatus', 
               'Get-PowerTypeHistory'

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'PowerShell','Prediction','Recommendation','Predictor'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/AnderssonPeter/PowerType/blob/main/LICENSE.md'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/AnderssonPeter/PowerType/'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/AnderssonPeter/PowerType/main/Icon.svg'

        # ReleaseNotes of this module
        ReleaseNotes = 'New feature: the dynamic items like git branches now support refresh when certain commands are executed.
This should hopefully solve the display of outdated suggestions.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        ExternalModuleDependencies = @('PSReadLine')

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

